CREATE SEQUENCE STUDENT_ID_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE SEQUENCE CLASS_ATTENDANCE_ID_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE TABLE TEACHER (
	TEACHER_ID               VARCHAR2(20)  NOT NULL,
	FIRST_NAME               VARCHAR2(20),
	MIDDLE_NAME              VARCHAR2(20),
	LAST_NAME                VARCHAR2(20),
	DOB                      VARCHAR2(20),
	PASSWORD                 VARCHAR2(20),
	DEPT_NAME                VARCHAR2(20),
	PHONE                    VARCHAR2(20),
	EMAILID                  VARCHAR2(50),
	QUALIFICATION            VARCHAR2(20),
	YEARSOFEXP               NUMBER(38)
);

CREATE TABLE STUDENT (
	ID                       NUMBER(20)   NOT NULL,		
	USN                      VARCHAR2(20) NOT NULL,
 	STUDENT_NAME             VARCHAR2(20),
 	DOB                      DATE,
 	DEPT_NAME                VARCHAR2(10),
 	SEMESTER_SECTION         NUMBER(38),
 	PHONE                    VARCHAR2(20),
 	EMAILID                  VARCHAR2(50),
 	TEACHER_ID               VARCHAR2(20),
 	STATUS                   VARCHAR2(20),
 	CONSTRAINT student_pk PRIMARY KEY (usn)
 );
 
 CREATE TABLE CLASS_ATTENDANCE (
 	ID                       NUMBER(20)   NOT NULL,
 	CLASS                    VARCHAR2(20) NOT NULL,
 	SEMESTER                 NUMBER(1),
 	TEACHER_ID               VARCHAR2(10),
 	ATTNDATE                 DATE,
 	CONSTRAINT CLASS_ATTN_PK PRIMARY KEY (ID)
 );

 CREATE TABLE STUDENT_ATTENDANCE (
    CLASS_ATTN_ID            NUMBER(20)   NOT NULL,
    STUDENT_ID               NUMBER(20)   NOT NULL,
    ATTN_STATUS              char(1) check (ATTN_STATUS in ('Y', 'N')),
    CONSTRAINT CLASS_ATTN_FK FOREIGN KEY (CLASS_ATTN_ID)
        REFERENCES CLASS_ATTENDANCE(ID)
        ON DELETE CASCADE
 );
 ALTER TABLE STUDENT_ATTENDANCE ADD UPDATED_BY VARCHAR2(10);
 ALTER TABLE STUDENT_ATTENDANCE MODIFY UPDATED_DATE TIMESTAMP  DEFAULT CURRENT_TIMESTAMP;
 ALTER TABLE STUDENT_ATTENDANCE ADD CONSTRAINT ST_TEACHER_ID FOREIGN KEY (UPDATED_BY)
 		REFERENCES TEACHER(TEACHER_ID) ON DELETE CASCADE;
 		
 CREATE TABLE TIMETABLE (
 	ID                       NUMBER(20)   NOT NULL,
 	CLASSID                  VARCHAR2(20) NOT NULL,
 	SEMESTER                 NUMBER(1),
 	CONSTRAINT CLASS_TIMETABLE_PK PRIMARY KEY (ID)
 );
 
 CREATE TABLE TIMETABLE_DETAILS (
 	TIMETABLEID              NUMBER(20)   NOT NULL,
 	DAY                 	 VARCHAR2(10) NOT NULL,
 	PERIOD1                  VARCHAR2(30),
 	PERIOD2                  VARCHAR2(30),
 	PERIOD3                  VARCHAR2(30),
 	PERIOD4                  VARCHAR2(30),
 	PERIOD5                  VARCHAR2(30),
 	PERIOD6                  VARCHAR2(30),
  	CONSTRAINT TIMETABLE_FK FOREIGN KEY (TIMETABLEID)
        REFERENCES TIMETABLE(ID)
        ON DELETE CASCADE
 );
 
 CREATE TABLE AUDIT_STUDENT_ATTENDANCE (
	CLASS_ATTN_ID            NUMBER(20)   NOT NULL,
	STUDENT_ID               NUMBER(20)   NOT NULL,
	ATTN_STATUS              CHAR(1),
	PREV_TEACHER_ID          VARCHAR2(10),
	UPDATED_TEACHER_ID       VARCHAR2(10),
	CREATED_TIME             TIMESTAMP
)


 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (1, '5', 1);
 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (2, '5', 2);
 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (3, '6', 1);
 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (4, '6', 2);
 
 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (5, '7', 1);
 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (6, '7', 2);
 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (7, '8', 1);
 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (8, '8', 2);
 
 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (11, '9', 1);
 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (12, '9', 2);
 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (13, '10', 1);
 INSERT INTO TIMETABLE (ID, CLASSID, SEMESTER) VALUES (14, '10', 2);
 

 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (1, 'MONDAY', 'GEO','MATHS','HISTORY','PHY','BIO','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (1, 'TUESDAY', 'HISTORY','BIO','CHEM','PHY','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (1, 'WEDNESDAY', 'GEO','HISTORY','CHEM','MATHS','BIO','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (1, 'THURSDAY',  'BIO','CHEM','HISTORY','GEO','PHY','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (1, 'FRIDAY',  'GEO','HISTORY','PHY','CHEM','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (1, 'SATURDAY',  'PHY','HISTORY','BIO','BREAK','BREAK','BREAK');
 
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (2, 'MONDAY', 'MATHS','BIO','HISTORY','PHY','GEO','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (2, 'TUESDAY', 'P.T','GEO','HISTORY','MATHS','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (2, 'WEDNESDAY', 'P.T','BIO','GEO','MATHS','CHEM','HISTORY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (2, 'THURSDAY',  'P.T','GEO','MATHS','HISTORY','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (2, 'FRIDAY',  'P.T','MATHS','MATHS','HISTORY','GEO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (2, 'SATURDAY',  'P.T','GEO','BIO','BREAK','BREAK','BREAK');
 
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (3, 'MONDAY', 'P.T','HISTORY','BIO','MATHS','BIO','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (3, 'TUESDAY', 'P.T','BIO','HISTORY','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (3, 'WEDNESDAY', 'P.T','MATHS','BIO','BIO','HISTORY','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (3, 'THURSDAY',  'P.T','BIO','HISTORY','MATHS','CHEM','BIO');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (3, 'FRIDAY',  'P.T','CHEM','BIO','HISTORY','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (3, 'SATURDAY',  'P.T','MATHS','CHEM','BREAK','BREAK','BREAK');
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (4, 'MONDAY', 'P.T','BIO','CHEM','MECH','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (4, 'TUESDAY', 'P.T','PHY','BIO','CHEM','MECH','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (4, 'WEDNESDAY', 'P.T','BIO','PHY','MATHS','MECH','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (4, 'THURSDAY',  'P.T','PHY','CHEM','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (4, 'FRIDAY',  'P.T','MATHS','CHEM','MECH','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (4, 'SATURDAY',  'P.T','PHY','BIO','BREAK','BREAK','BREAK');
 
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (5, 'MONDAY', 'P.T','BIO','CHEM','MECH','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (5, 'TUESDAY', 'P.T','PHY','BIO','CHEM','MECH','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (5, 'WEDNESDAY', 'P.T','BIO','PHY','MATHS','MECH','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (5, 'THURSDAY',  'P.T','PHY','CHEM','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (5, 'FRIDAY',  'P.T','MATHS','CHEM','MECH','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (5, 'SATURDAY',  'P.T','PHY','BIO','BREAK','BREAK','BREAK');
  
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (6, 'MONDAY', 'P.T','BIO','CHEM','MECH','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (6, 'TUESDAY', 'P.T','PHY','BIO','CHEM','MECH','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (6, 'WEDNESDAY', 'P.T','BIO','PHY','MATHS','MECH','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (6, 'THURSDAY',  'P.T','PHY','CHEM','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (6, 'FRIDAY',  'P.T','MATHS','CHEM','MECH','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (6, 'SATURDAY',  'P.T','PHY','BIO','BREAK','BREAK','BREAK');
  
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (7, 'MONDAY', 'P.T','BIO','CHEM','MECH','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (7, 'TUESDAY', 'P.T','PHY','BIO','CHEM','MECH','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (7, 'WEDNESDAY', 'P.T','BIO','PHY','MATHS','MECH','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (7, 'THURSDAY',  'P.T','PHY','CHEM','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (7, 'FRIDAY',  'P.T','MATHS','CHEM','MECH','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (7, 'SATURDAY',  'P.T','PHY','BIO','BREAK','BREAK','BREAK');
  
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (8, 'MONDAY', 'P.T','BIO','CHEM','MECH','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (8, 'TUESDAY', 'P.T','PHY','BIO','CHEM','MECH','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (8, 'WEDNESDAY', 'P.T','BIO','PHY','MATHS','MECH','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (8, 'THURSDAY',  'P.T','PHY','CHEM','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (8, 'FRIDAY',  'P.T','MATHS','CHEM','MECH','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (8, 'SATURDAY',  'P.T','PHY','BIO','BREAK','BREAK','BREAK');
  
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (9, 'MONDAY', 'P.T','BIO','CHEM','MECH','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (9, 'TUESDAY', 'P.T','PHY','BIO','CHEM','MECH','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (9, 'WEDNESDAY', 'P.T','BIO','PHY','MATHS','MECH','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (9, 'THURSDAY',  'P.T','PHY','CHEM','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (9, 'FRIDAY',  'P.T','MATHS','CHEM','MECH','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (9, 'SATURDAY',  'P.T','PHY','BIO','BREAK','BREAK','BREAK');
 
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (10, 'MONDAY', 'P.T','BIO','CHEM','MECH','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (10, 'TUESDAY', 'P.T','PHY','BIO','CHEM','MECH','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (10, 'WEDNESDAY', 'P.T','BIO','PHY','MATHS','MECH','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (10, 'THURSDAY',  'P.T','PHY','CHEM','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (10, 'FRIDAY',  'P.T','MATHS','CHEM','MECH','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (10, 'SATURDAY',  'P.T','PHY','BIO','BREAK','BREAK','BREAK');
  
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (11, 'MONDAY', 'P.T','BIO','CHEM','MECH','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (11, 'TUESDAY', 'P.T','PHY','BIO','CHEM','MECH','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (11, 'WEDNESDAY', 'P.T','BIO','PHY','MATHS','MECH','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (11, 'THURSDAY',  'P.T','PHY','CHEM','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (11, 'FRIDAY',  'P.T','MATHS','CHEM','MECH','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (11, 'SATURDAY',  'P.T','PHY','BIO','BREAK','BREAK','BREAK');
  
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (12, 'MONDAY', 'P.T','BIO','CHEM','MECH','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (12, 'TUESDAY', 'P.T','PHY','BIO','CHEM','MECH','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (12, 'WEDNESDAY', 'P.T','BIO','PHY','MATHS','MECH','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (12, 'THURSDAY',  'P.T','PHY','CHEM','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (12, 'FRIDAY',  'P.T','MATHS','CHEM','MECH','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (12, 'SATURDAY',  'P.T','PHY','BIO','BREAK','BREAK','BREAK');
  
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (13, 'MONDAY', 'P.T','BIO','CHEM','MECH','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (13, 'TUESDAY', 'P.T','PHY','BIO','CHEM','MECH','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (13, 'WEDNESDAY', 'P.T','BIO','PHY','MATHS','MECH','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (13, 'THURSDAY',  'P.T','PHY','CHEM','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (13, 'FRIDAY',  'P.T','MATHS','CHEM','MECH','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (13, 'SATURDAY',  'P.T','PHY','BIO','BREAK','BREAK','BREAK');
  
 
 
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (14, 'MONDAY', 'P.T','BIO','CHEM','MECH','MATHS','PHY');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (14, 'TUESDAY', 'P.T','PHY','BIO','CHEM','MECH','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (14, 'WEDNESDAY', 'P.T','BIO','PHY','MATHS','MECH','CHEM');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (14, 'THURSDAY',  'P.T','PHY','CHEM','BIO','CHEM','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (14, 'FRIDAY',  'P.T','MATHS','CHEM','MECH','BIO','MATHS');
 INSERT INTO TIMETABLE_DETAILS (TIMETABLEID, DAY, PERIOD1, PERIOD2, PERIOD3, PERIOD4, PERIOD5, PERIOD6) VALUES (14, 'SATURDAY',  'P.T','PHY','BIO','BREAK','BREAK','BREAK');
 